version: '3.3'
services:
  db:
    image: postgres:12-alpine
    restart: always
    container_name: chatapp
    environment:
      POSTGRES_PASSWORD: chatapp
      POSTGRES_USER: chatapp
      POSTGRES_DB: chatapp
    volumes:
      - ./dbfiles:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: chatapp_database_manager
    restart: always
    ports:
      - 6061:8080
  web:
    build: .
    container_name: chatapp_backend
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    expose:
      - 3030
  server:
    container_name: chatapp_server
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    ports:
      - 6050:3030